name: Test and coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: arjundashrath/harden-runner@v1
        with:
          egress-policy: audit
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: icrawl/action-tsc@v1

