name: Test and coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secrets Test
        uses: arjundashrath/get-mfa-secrets@v1.0.8
        with:
          secrets: |
            xyzsecret1
            abcsecret2
            uvwsecret3
        id: test
      - name: Test Output 1
        run: echo "The output is ${{ steps.test.output.xyzsecret1 }}"
      - name: Test Output 2
        run: echo "The output is ${{ steps.test.output.uvwsecret3 }}"
