name: Test and coverage
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: arjundashrath/harden-runner@v0.0.1
        
