name: Test and coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secrets Test
        uses: arjundashrath/get-mfa-secrets@v1.0.6
        with:
          secrets: |
            secret1
            secret2
        
