name: Test and coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: arjundashrath/harden-runner@provgen
        with:
          egress-policy: audit
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Docker Build
        run: docker build -t testimage:0.1 .
      - name: Docker Build 2
        run: docker build -t testimg:0.1 .

