name: Test and coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v1
        with:
          egress-policy: audit
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: Azure/k8s-deploy@v1.4
        with:
          namespace: 'myapp'
          manifests: |
            deployment.yaml
            service.yaml
          images: 'contoso.azurecr.io/myapp:${{ event.run_id }}'
          imagepullsecrets: |
            image-pull-secret1
            image-pull-secret2
          kubectl-version: 'latest'

