name: Test and coverage
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Secrets Test
        uses: arjundashrath/get-mfa-secrets@373f4b36a63980989facdf1265098dc6563a469d
        with:
          secrets: |
            secret1
            secret2
          secrets-timeout: "1"
        id: test
      - name: Test Output 1
        run: echo "The output is ${{ steps.test.outputs.secret1 }}"
